include: package:very_good_analysis/analysis_options.yaml

analyzer:
    exclude:
        - pubspec.yaml
        - lib/env.dart
        - lib/env.g.dart

linter:
  rules:
    # パブリックなメンバ変数・メソッドにドキュメントコメントを要求するルール
    public_member_api_docs: false # https://dart.dev/tools/linter-rules/public_member_api_docs
