name: nost
description: A unique storytelling travel app.

publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  package_info_plus: ^4.2.0
  envied: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  cider: ^0.2.4
  envied_generator: ^0.5.2

flutter:
  uses-material-design: true
