name: nost
description: A unique storytelling travel app.

publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cider: ^0.2.4

flutter:
  uses-material-design: true
